### ISSUE TITLE
报错 nginx: invalid option: "echo"

### ISSUE THREAD

**Issue by BlackSWAE** [IITII/VNSTAT-DASHBOARD#1]
![Snipaste_2022-08-28_09-53-25](https://user-images.githubusercontent.com/103973243/187054138-29b0fc41-f569-441d-a442-93ef7fd64fea.jpg)
 
这是哪里搞错了吗

**Comment by IITII** [comment]
* __用这个自动发布的最新版就行了。[iitii.github.io/vnstat-dashboard/](https://iitii.github.io/VNSTAT-DASHBOARD/)__

1. 你命令是错的。 
2. readme 里面是以前版本的，还没来得及改。

* 自己要本地弄的话下 release 里面的 zip.zip， 解压到网站根目录就行
