### ISSUE TITLE
找不到default文件

### ISSUE THREAD

**Issue by dfmjndm** [IITII/VNSTAT-DASHBOARD#2]
centos7的nginx目录格式不一样找不到default，我参考https://www.cnblogs.com/aduner/p/14224858.html 做了修改
可以发下default的文件内容吗

Log:
[root@iZohsgoqg2z7njZ vnstat]# sudo service nginx restart
Redirecting to /bin/systemctl restart nginx.service
[root@iZohsgoqg2z7njZ vnstat]# sed -i "s/root \S\+/root \/var\/www\/vnstat;/g" /etc/nginx/sites-available/default \
> && nginx -t && nginx -s reload \
> echo "1 * * * * /usr/bin/vnstat --json > /var/www/vnstat/vnstat.json" \
> >> /var/spool/cron/crontabs/`whoami`
sed: can't read /etc/nginx/sites-available/default: No such file or directory
[root@iZohsgoqg2z7njZ vnstat]# crontab -l

**Comment by IITII** [comment]
示例是 Ubuntu 环境，centos 不清楚

> 搞不定的话，直接用这个 demo也可以 https://iitii.github.io/VNSTAT-DASHBOARD/  

```nginx
server {
    listen 80 default_server;
    server_name _;
    location / {
        root /var/www/html;
        # alias /usr/share/nginx/html;
        index index.html index.htm;
    }
}
```

**Comment by dfmjndm** [comment]
已解决
cron位置是/var/spool/cron
default用的是/etc/nginx/nginx.conf
