### ISSUE TITLE
指令少打一个字，install输入成了insall

### ISSUE THREAD

**Issue by koi5hi** [IITII/VNSTAT-DASHBOARD#3]
代码栏里的
`apt insall nginx vnstat -y`
这里的insall的单词错误了，这边复制直接粘贴进去提示
`apt insall nginx vnstat -y
E: Invalid operation insall`
可以改一下改成 install

**Comment by IITII** [comment]
ok，明天看看

koi5hi ***@***.***> 于 2023年4月27日周四 02:27写道：
